"""
Person 1: Search & Query Specialist
Simplified version that collects raw search results from OpenAI web search.
"""

import json
from typing import List, Dict, Any
import sys
from pathlib import Path

# Add parent directory to path for imports
sys.path.append(str(Path(__file__).parent.parent))

from config.env_config import get_openai_api_key
from person1.search_orchestrator import SearchOrchestrator as RealSearchOrchestrator
from person1.query_expansion import expand_query


class QueryExpander:
    """
    Expands a single topic into multiple well-phrased queries.
    This now delegates to the dedicated GPT-powered expand_query function.
    """

    @staticmethod
    def expand_topic(topic: str, grade: str = "elementary") -> List[str]:
        """
        Turn a single topic into multiple well-phrased queries using GPT.

        Args:
            topic: The main topic (e.g., "Photosynthesis")
            grade: Grade level (e.g., "elementary", "middle", "high")

        Returns:
            List of expanded queries (up to 7), generated by expand_query().
        """
        # Map internal grade labels to something friendlier for the LLM, if needed.
        grade_str = None
        if grade:
            # You can customize this mapping if you like.
            if grade.lower() == "elementary":
                grade_str = "elementary school"
            elif grade.lower() == "middle":
                grade_str = "middle school"
            elif grade.lower() == "high":
                grade_str = "high school"
            else:
                grade_str = grade

        return expand_query(topic, grade_str)


# Use the proper SearchOrchestrator from search_orchestrator.py instead of a broken implementation
# The SearchOrchestrator class is now imported from search_orchestrator module


class RawResultCollector:
    """Main collector that combines query expansion and search."""
    
    def __init__(self, api_key: str = None):
        """Initialize the collector."""
        self.query_expander = QueryExpander()
        # Use the proper SearchOrchestrator from search_orchestrator.py
        self.search_orchestrator = RealSearchOrchestrator(api_key)
    
    def collect_raw(self, topic: str, grade: str = "elementary") -> List[Dict[str, Any]]:
        """
        Collect raw search results for a topic.
        
        Args:
            topic: The educational topic
            grade: Grade level
            
        Returns:
            List of 15-20 raw search result items
        """
        print(f"Collecting raw results for topic: {topic} (grade: {grade})")
        
        # Expand queries
        queries = self.query_expander.expand_topic(topic, grade)
        print(f"Generated {len(queries)} search queries")
        
        # Search for each query
        all_results = []
        for i, query in enumerate(queries, 1):
            print(f"Searching query {i}/{len(queries)}: {query}")
            results = self.search_orchestrator.search(query, max_results=4)
            all_results.extend(results)
        
        # Remove duplicates based on URL
        seen_urls = set()
        unique_results = []
        for result in all_results:
            url = result.get("url", "")
            if url and url not in seen_urls:
                seen_urls.add(url)
                unique_results.append(result)
        
        print(f"Collected {len(unique_results)} unique results")
        return unique_results[:20]  # Return up to 20 items


def main():
    """Demo function."""
    import sys
    
    if len(sys.argv) < 2:
        print("Usage: python search_collector.py <topic> [grade]")
        print("Example: python search_collector.py 'Photosynthesis' 'elementary'")
        sys.exit(1)
    
    topic = sys.argv[1]
    grade = sys.argv[2] if len(sys.argv) > 2 else "elementary"
    
    collector = RawResultCollector()
    results = collector.collect_raw(topic, grade)
    
    # Save to JSON
    output_file = Path(__file__).parent.parent / "data" / "raw" / f"{topic.replace(' ', '_')}_raw.json"
    output_file.parent.mkdir(parents=True, exist_ok=True)
    
    with open(output_file, 'w', encoding='utf-8') as f:
        json.dump(results, f, indent=2, ensure_ascii=False)
    
    print(f"\nSaved {len(results)} results to: {output_file}")
    print(f"\nSample result:")
    if results:
        print(json.dumps(results[0], indent=2))


if __name__ == "__main__":
    main()
